# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7
language: objective-c
# cache: cocoapods
podfile: Example/Podfile
before_install:
# - gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild -workspace Example/MXSegmentedPager.xcworkspace -scheme MXSegmentedPager-Example -sdk iphonesimulator -configuration Release -destination "platform=iOS Simulator,name=iPhone 6" test | xcpretty -c
- pod lib lint --quick
